### ISSUE TITLE
System.MissingMethodException: Method not found: 'Hopac.Job`1...

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [brokenprogrammer/BrokenDiscord#50]
### F# interactive window attempt:

Reflection shows the following are loaded:

> mscorlib - "4.0.0.0" - C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
> Hopac.Core - 0.3.23.0
> Hopac - 0.3.23.0
> FSharp.Core - 4.5.0.0
> FSharp.Control.AsyncSeq - 2.0.21.0
> BrokenDiscord - 1.0.0.0
> https://gist.github.com/ImaginaryDevelopment/b99cd55a70fd0b4faba09bf06d34f3ab

fails with 
> `stdin(230,25): error FS0074: The type referenced through 'FSharp.Control.AsyncSeq`1' is defined in an assembly that is not referenced. You must add a reference to assembly 'FSharp.Control.AsyncSeq'`

on the line `if m.content = "!ping" then`
gist at: https://gist.github.com/ImaginaryDevelopment/b99cd55a70fd0b4faba09bf06d34f3ab

### LinqPad attempt:

LINQPad 5 Premium 5.31.00 when trying to `!ping` in chat for the first time it says:

```
Listening for pings...
WARNING: You are using single-threaded workstation garbage collection, which means that parallel programs cannot scale.  Please configure your program to use server garbage collection.
Unhandled exception: System.MissingMethodException: Method not found: 'Hopac.Job`1<Microsoft.FSharp.Core.FSharpResult`2<Message,ApiError>> Client.CreateMessage(UInt64, T)'.
   at <StartupCode$query_iqzixz>.$Query_iqzixz.pong@42-1.Invoke(Unit unitVar)
   at Hopac.Core.JobDelay`1.DoJob(Worker& wr, Cont`1 xK)
   at Hopac.Core.Worker.RunOnThisThread[T](Scheduler sr, Job`1 tJ, Cont`1 tK)
No other causes.
```

Reflection shows the following assemblies loaded if I ask it to check right before `client.start()`

Newtonsoft.Json - "11.0.0.0"
FSharp.Core - 4.5.0.0
mscorlib - 4.0.0.0
LINQPad - 1.0.0.0
BrokenDiscord - 1.0.0.0
Hopac - "0.3.23.0"
Hopac.Core - 0.3.23.0

Full script code at:

https://github.com/ImaginaryDevelopment/LinqPad/blob/master/LINQPad%20Queries/WIP/DiscordBot.linq

**Comment by brokenprogrammer** [comment]
Hey, I'll try take a closer look at this issue as soon as time allows it. I've never tried using BrokenDiscord as a script neither through interactive or linqpad.

Great that you attached your gist so that I have something to test against!

Quick look at the problem it seems to be issues when it comes to loading the dependencies when running from F# interactive. I've managed to reproduce this problem and I'll update this issue once I find out more.
